server:
  port: 80

spring:
  application:
    name: cloud-test-one
  datasource:
    username: root
    password: '@aysz520888'
    url: jdbc:mysql://localhost:3306/administration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


