server:
  port: 8001

spring:
  application:
    name: cloud-test-one
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@aysz520888'
    url: jdbc:mysql://localhost:3306/administration
  redis:
    port: 6379
    host: 192.168.91.129
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka